### ISSUE TITLE
Using ubuntu:xenial as base image

### ISSUE THREAD

**Issue by knutole** [mapsquare/docker-mapnik3#1]
Getting lots of package errors when trying to use `ubuntu:xenial` image. Any pointers on how to create a working xenial image? 

```bash
E: Package 'librasterlite-dev' has no installation candidate
E: Unable to locate package libboost-filesystem1.55.0
E: Couldn't find any package by glob 'libboost-filesystem1.55.0'
E: Couldn't find any package by regex 'libboost-filesystem1.55.0'
E: Unable to locate package libboost-program-options1.55.0
E: Couldn't find any package by glob 'libboost-program-options1.55.0'
E: Couldn't find any package by regex 'libboost-program-options1.55.0'
E: Unable to locate package libboost-regex1.55.0
E: Couldn't find any package by glob 'libboost-regex1.55.0'
E: Couldn't find any package by regex 'libboost-regex1.55.0'
E: Unable to locate package libboost-thread1.55.0
E: Couldn't find any package by glob 'libboost-thread1.55.0'
E: Couldn't find any package by regex 'libboost-thread1.55.0'
E: Unable to locate package libboost-system1.55.0
E: Couldn't find any package by glob 'libboost-system1.55.0'
E: Couldn't find any package by regex 'libboost-system1.55.0'
E: Package 'libgdal1h' has no installation candidate
E: Unable to locate package libicu52
E: Unable to locate package libjpeg62-turbo
E: Unable to locate package libproj0
E: Unable to locate package librasterlite2
```

Great repo, btw, thanks!

**Comment by Joxit** [comment]
Hi @knutole,

thanks for your issue.
We provided the image as a derivate from debian Jessie because it matches most of our environment structure and it is lightweight enough.
If you want to make your own with ubuntu, you might want to take a look at the package names.
Don't hesitate to use apt-cache search commands and find the equivalent libraries in ubuntu.
Versions might also differ as ubuntu packages them in a different way and at a different point in time.

For instance, the lib `librasterlite-dev` in ubuntu is called `librasterlite2-dev`.

**Comment by knutole** [comment]
Thanks @Joxit, I'll see what I can do. I'll post back for reference.
