### ISSUE TITLE
python plugin

### ISSUE THREAD

**Issue by kathur2rain** [mapsquare/docker-mapnik3#7]
it seems no python plugin was built in this image, but python plugin was listed in the default Mapnik build. 
![image](https://user-images.githubusercontent.com/50347748/59254475-d59c8880-8c62-11e9-867c-ac18fb891a64.png)

Would you consider build it? or can I simply add a line in dockerfile to build it?

**Comment by Joxit** [comment]
Hi,
Be careful, this is an experimental plugin, that's why this is not include it in the image.
Furthermore, this plugin is not included in their plugin list here 

https://github.com/mapnik/mapnik/blob/46478d4b5a17e4a66bd81af59175e21c493712af/SConstruct#L125-L139 

If you know the way to install this plugin, tell us and we will consider to add it in our image.

**Comment by kathur2rain** [comment]
thanks for the rep, I understand about the risk and will try to test it. close issue
